### ISSUE TITLE
Conflict with addon zUI

### ISSUE THREAD

**Issue by PhoenixHope** [Nonameby/Atlas#5]
When Atlas is enabled and zUI as well, a whole action bar becomes unusable. At reload not noticeable, but when you click the bottom right actionbar(as you see it - might not actually be bottom right because zUI shuffles them) on screen, the actionbar's icons disappear, like another empty action bar is placed on top.

settings: all action bars enabled
any settings of zUI BFA and non BFA style

**Comment by Nonameby** [comment]
I will check it out

**Comment by Nonameby** [comment]
> When Atlas is enabled and zUI as well, a whole action bar becomes unusable. At reload not noticeable, but when you click the bottom right actionbar(as you see it - might not actually be bottom right because zUI shuffles them) on screen, the actionbar's icons disappear, like another empty action bar is placed on top.
> 
> settings: all action bars enabled any settings of zUI BFA and non BFA style

I will check it out

**Comment by Nonameby** [comment]
temporary fix
